vpc_name             = "demo-vpc"
public_subnet        = "public-subnet-1"
public_subnet_cidrs  = "10.0.1.0/24"
private_subnet       = "private-subnet-1"
private_subnet_cidrs = "10.0.2.0/24"
cluster_name         = "demo-gke-cluster"
