name: ad-service-ci

on:
  pull_request:
    branches: [main]
  push:
    paths:
      - '.github/workflows/ad.yaml'
      - 'src/ad/**'
  pull_request_target:
    branches: [main]
    paths:
      - '.github/workflows/ad.yaml'
      - 'src/ad/**'

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Give Gradle permission to execute
        run: chmod +x ./src/ad/gradlew

      - name: Run unit tests
        working-directory: ./src/ad
        run: ./gradlew test

  # ✅ Stage 2: Code Quality
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Give Gradle permission to execute
        run: chmod +x ./src/ad/gradlew

      - name: Run Google Java Format Check
        working-directory: ./src/ad
        run: ./gradlew verifyGoogleJavaFormat
        continue-on-error: true

  # ✅ Stage 3: Docker Build, Trivy Scan, and Push to Google Artifact Registry
  docker-build-push:
    runs-on: ubuntu-latest
    needs: code-quality  # Now depends on the code-quality job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/ad:${{ github.sha }} -f src/ad/Dockerfile ./src/ad

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/ad:${{ github.sha }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vulnerability-type: 'os,library'

      - name: Push Docker Image to GAR
        run: |
          docker push asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/ad:${{ github.sha }}

  update-and-push-k8s:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: Update ad-service image tag and push if changed
        run: |
          git config --global user.email "mspr9773@gmail.com"
          git config --global user.name "mokadi surya prasad"

          sed -i "s|image: .*|image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/ad:${{ github.sha }}|" kubernetes/ad/deploy.yaml

          git add kubernetes/ad/deploy.yaml

          # Commit only if there are actual changes
          if ! git diff --cached --quiet; then
            git commit -m "[CI] Update ad image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes detected in deploy.yaml. Skipping commit and push."
