name: checkout-service-ci

on:
  pull_request:
    branches: [main]
  push:
    paths:
      - '.github/workflows/checkout.yaml'
      - 'src/checkout/**'
  pull_request_target:
    branches: [main]
    paths:
      - '.github/workflows/checkout.yaml'
      - 'src/checkout/**'

jobs:
  # ✅ Stage 1: Unit Testing
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run Unit Tests
        working-directory: ./src/checkout
        run: |
          go mod download
          go test -v ./...

  # ✅ Stage 2: Code Quality with golangci-lint
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        working-directory: ./src/checkout
        run: |
          go mod tidy
          golangci-lint run ./... --timeout 5m

  # ✅ Stage 3: Docker Build, Trivy Scan, and Push to Google Artifact Registry
  docker-build-push:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/checkout:${{ github.sha }} -f src/checkout/Dockerfile .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/checkout:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true

      - name: Push Docker Image to GAR
        run: |
          docker push asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/checkout:${{ github.sha }}

  # ✅ Stage 4: Update Kubernetes YAML and Push if Changed
  update-and-push-k8s:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: Update checkout-service image tag and push if changed
        run: |
          git config --global user.email "mspr9773@gmail.com"
          git config --global user.name "mokadi surya prasad"

          # Update the image tag in deploy.yaml
          sed -i "s|image: .*|image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/checkout:${{ github.sha }}|" kubernetes/checkout/deploy.yaml

          # Add changes
          git add kubernetes/checkout/deploy.yaml

          # Commit only if there are actual changes
          if ! git diff --cached --quiet; then
            git commit -m "[CI] Update checkout image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes detected in deploy.yaml. Skipping commit and push."
          fi
