name: product-catalog-service-ci

on:
  push:
    paths:
      - '.github/workflows/product-catalog-ci.yaml'
      - 'src/productcatalog/**'
  #pull_request:
    #branches: [main]

jobs:
  # ✅ Stage 1: Unit Testing
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: |
          cd src/checkout
          go mod download
          go build -o checkout main.go

      - name: Run unit tests
        run: |
          cd src/checkout
          go test -v ./...

  # ✅ Stage 2: Code Quality with golangci-lint
  code-quality:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow the pipeline to continue even if linting fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint with config file
        working-directory: ./src/checkout
        run: |
            go mod tidy
            golangci-lint run --config .golangci.yml --timeout 5m

  # ✅ 3. Docker Build, Trivy Scan, and Push to GAR
  docker-build-push:
    runs-on: ubuntu-latest
    needs: [unit-testing, code-quality]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use GAR
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/productcatalogservice:${{ github.sha }} -f src/product-catalog/ .

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/productcatalogservice:${{ github.sha }}
          format: table
          exit-code: '0'
          ignore-unfixed: true

      - name: Push Docker Image to GAR
        run: |
          docker push asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/productcatalogservice:${{ github.sha }}

  # ✅ 4 & 5. Update K8s Manifest and Git Commit+Push
  update-k8s-and-push:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: Update manifest and commit changes
        run: |
          git config --global user.email "mspr9773@gmail.com"
          git config --global user.name "mokadi surya prasad"

          # Update image
          sed -i "s|image: .*|image: asia-south1-docker.pkg.dev/silken-oxygen-454215-v6/microservices-demo/productcatalogservice:${{ github.sha }}|" kubernetes/productcatalog/deployment.yaml
          echo "Updated Manifest:"
          cat kubernetes/product-catalog/deployment.yaml

          # Commit only if there are changes
          git add kubernetes/product-catalog/deployment.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[CI] Update product-catalog deployment image tag"
            git push
          fi
